### ISSUE TITLE
Trouble installing that package

### ISSUE THREAD

**Issue by Ennyization** [mlux86/flowLearn#2]
Hello I am a R noob
I am having trouble getting this package to install. I have spent a couple of nights trying to do my own troubleshooting but I am stuck. 
This is what I am seeing.

![FlowLearn Error](https://user-images.githubusercontent.com/13210013/68267495-382e6080-0018-11ea-9ed9-10327f602a40.PNG)

After all my googling I am guessing that this is happening because ddp or dd are empty and returning a Null when called by flAt. 

![117-126](https://user-images.githubusercontent.com/13210013/68267720-023dac00-0019-11ea-9314-b6e8aa00cb49.PNG)

Like I said I am completely new to R and have very limited programming knowledge so I might be completely off base here. 
Any guidance would be appreciated. Thank you

**Comment by ryanrbrinkman** [comment]
It seems you are working in a Windows environment. We do not have access to such a setup, but were unable to replicate your error message under Linux (Ubtuntu).


You should use the code at the following link to install flowLearn(it is the official page of flowLearn on github):
https://rdrr.io/github/mlux86/flowLearn/

This is the code to install flowLearn:

install.packages("remotes")
remotes::install_github("mlux86/flowLearn",force = TRUE)

We have tested this on our own systems and it works without error. If you are doing this from within RStudio    Rstudio  must be opened with administrator privileges.

Thanks for your interest in flowLearn, I hope this helps.

-Ryan




On Nov 5, 2019, at 8:13 PM, Scott E <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello I am a R noob
I am having trouble getting this package to install. I have spent a couple of nights trying to do my own troubleshooting but I am stuck.
This is what I am seeing.

[FlowLearn Error]<https://user-images.githubusercontent.com/13210013/68267495-382e6080-0018-11ea-9ed9-10327f602a40.PNG>

After all my googling I am guessing that this is happening because ddp or dd are empty and returning a Null when called by flAt.

[117-126]<https://user-images.githubusercontent.com/13210013/68267720-023dac00-0019-11ea-9314-b6e8aa00cb49.PNG>

Like I said I am completely new to R and have very limited programming knowledge so I might be completely off base here.
Any guidance would be appreciated. Thank you

**Comment by Ennyization** [comment]
I got the package to install. Thank you so much for help. Keep up the good work making all the awesome utilities for handling flow data.
